// bootstrap-helpers.ts — Pure helper functions extracted from bootstrap-app.ts
// These functions are standalone (explicit params, no closures over bootstrap locals).

import type { ILoggerPort } from '@manta/core'
import type { IRepositoryFactory } from '@manta/core/ports'
import type postgres from 'postgres'

// ── DML entity type guard ─────────────────────────────────────────

export interface DmlEntityLike {
  name: string
  schema: Record<string, unknown>
  getOptions?: () => Record<string, unknown>
}

export function isDmlEntity(value: unknown): value is DmlEntityLike {
  return (
    typeof value === 'object' &&
    value !== null &&
    'name' in value &&
    'schema' in value &&
    typeof (value as Record<string, unknown>).name === 'string'
  )
}

// ── Service class introspection type guard ────────────────────────

export function hasModelObjects(
  cls: unknown,
): cls is (new (...args: unknown[]) => unknown) & { $modelObjects: Record<string, unknown> } {
  return typeof cls === 'function' && '$modelObjects' in cls
}

// ── Raw SQL with unsafe() ─────────────────────────────────────────

type PostgresSql = ReturnType<typeof postgres>

// ====================================================================
// Helpers (internal)
// ====================================================================

/**
 * Entity name → table export name convention.
 * Product → products, InventoryItem → inventoryItems
 */
export function entityToTableKey(entityName: string): string {
  const name = entityName.charAt(0).toLowerCase() + entityName.slice(1)
  if (name.endsWith('s') || name.endsWith('x') || name.endsWith('ch') || name.endsWith('sh')) return `${name}es`
  if (name.endsWith('y') && !/[aeiou]y$/i.test(name)) return `${name.slice(0, -1)}ies`
  return `${name}s`
}

export function tryInstantiateService(
  ServiceClass: new (...args: unknown[]) => unknown,
  infraMap: Map<string, unknown>,
  repoFactory: IRepositoryFactory,
): unknown | null {
  try {
    // Detect createService() classes — they have $modelObjects set by the framework
    const modelObjects = hasModelObjects(ServiceClass) ? ServiceClass.$modelObjects : undefined
    if (modelObjects) {
      const firstEntry = Object.entries(modelObjects)[0]
      if (firstEntry) {
        const entityName = isDmlEntity(firstEntry[1]) ? firstEntry[1].name : firstEntry[0]
        try {
          const repo = repoFactory.createRepository(entityToTableKey(entityName))
          return new ServiceClass({ baseRepository: repo })
        } catch {
          // Table not registered — fall through to other instantiation strategies
        }
      }
    }

    if (ServiceClass.length === 0) return new ServiceClass()
    const name = ServiceClass.name || ''
    if (name === 'FileService' || name === 'FileModuleService') {
      const file = infraMap.get('IFilePort')
      if (file) return new ServiceClass(file)
    }
    const portKeys = ['IFilePort', 'IDatabasePort', 'ILoggerPort', 'IEventBusPort', 'ICachePort']
    for (const key of portKeys) {
      const port = infraMap.get(key)
      if (port) {
        try {
          return new ServiceClass(port)
        } catch {}
      }
    }
    return null
  } catch {
    return null
  }
}

/**
 * Generate .manta/types.ts — module augmentation for typed step proxy.
 * Scans discovered modules, finds DML entities, writes the type file.
 */
export async function generateMantaTypes(
  cwd: string,
  modules: Array<{ name: string; dirName?: string; entities: Array<{ name: string; modelPath: string }> }>,
  doImport: (path: string) => Promise<Record<string, unknown>>,
  logger: ILoggerPort,
): Promise<void> {
  const { existsSync, mkdirSync, writeFileSync } = await import('node:fs')
  const { resolve, relative } = await import('node:path')

  const mantaDir = resolve(cwd, '.manta', 'types')
  if (!existsSync(mantaDir)) mkdirSync(mantaDir, { recursive: true })

  // Collect entity info: module name → { entityExportName, entityName, relativePath }
  const entries: Array<{ moduleName: string; entityExportName: string; entityName: string; modulePath: string }> = []

  for (const modInfo of modules) {
    for (const entity of modInfo.entities) {
      try {
        const mod = await doImport(entity.modelPath)
        for (const [exportName, value] of Object.entries(mod)) {
          if (isDmlEntity(value) && typeof value.getOptions === 'function') {
            entries.push({
              moduleName: modInfo.name,
              entityExportName: exportName,
              entityName: value.name,
              modulePath: entity.modelPath,
            })
          }
        }
      } catch {
        // Entity model may not export DML entities
      }
    }
  }

  if (entries.length === 0) return

  // Build the type file
  const lines: string[] = [
    '// Auto-generated by manta dev — DO NOT EDIT',
    '// This file provides typed step.product.create(), step.inventoryItem.create(), etc.',
    '// Regenerated on every boot when modules change.',
    '',
  ]

  // Import statements
  for (const entry of entries) {
    const relPath = relative(mantaDir, entry.modulePath).replace(/\.ts$/, '')
    lines.push(`import type { ${entry.entityExportName} } from '${relPath}'`)
  }

  lines.push('')
  lines.push("declare module '@manta/core' {")
  lines.push('  interface MantaEntities {')
  for (const entry of entries) {
    lines.push(`    ${entry.moduleName}: typeof ${entry.entityExportName}`)
  }
  lines.push('  }')
  lines.push('}')
  lines.push('')

  const typesPath = resolve(mantaDir, 'types.ts')
  writeFileSync(typesPath, lines.join('\n'))
  logger.info(`[codegen] .manta/types.ts generated (${entries.length} entities)`)
}

// ── Framework schema migration system ─────────────────────────────────
//
// Bump FRAMEWORK_SCHEMA_VERSION whenever `applyFrameworkDdl` changes in a way
// that requires an existing deployment to re-run DDL. The version is stored
// in the `manta_schema_versions` table and gates whether migrations run on
// boot. Bumping it forces one (and only one) re-application per deployment.
export const FRAMEWORK_SCHEMA_VERSION = 1

// Advisory lock key — arbitrary int64 unique to Manta. `pg_advisory_xact_lock`
// serializes parallel boots (serverless cold starts, multi-worker) so exactly
// one process applies migrations at a time. Auto-released on COMMIT/ROLLBACK.
const MIGRATION_LOCK_KEY = 0x4d414e544101n // 'MANTA' + version byte

type TaggedSql = (strings: TemplateStringsArray, ...values: unknown[]) => Promise<unknown>
type BeginFn = (cb: (tx: TaggedSql & { begin?: BeginFn }) => Promise<unknown>) => Promise<unknown>
type TaggedSqlWithBegin = TaggedSql & { begin: BeginFn }

/**
 * Ensure Manta's framework-internal schema is at FRAMEWORK_SCHEMA_VERSION.
 *
 * Safe to call unconditionally on every boot (dev, prod, serverless). Uses
 * a Postgres advisory transaction lock so concurrent boots serialize on the
 * migration, and a version table so only the first boot of a new deploy
 * actually runs DDL. Subsequent boots see the current version and return.
 *
 * Framework tables (workflow_runs, workflow_checkpoints, events, job_executions,
 * workflow_progress, stats, cron_heartbeats) are Manta-owned — the user never
 * writes to them. That's why we manage them here rather than via `manta db:*`
 * migrations, which is the app-level migration surface.
 */
export async function ensureFrameworkSchema(sql: unknown, logger: ILoggerPort): Promise<void> {
  const pg = sql as TaggedSqlWithBegin

  // 1. Meta table — CREATE IF NOT EXISTS is atomic in Postgres; safe if
  //    multiple boots race here before the lock is acquired.
  await pg`
    CREATE TABLE IF NOT EXISTS manta_schema_versions (
      name TEXT PRIMARY KEY,
      version INTEGER NOT NULL,
      applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `

  // 2. Acquire lock + version-gate + apply DDL in a single transaction.
  //    pg_advisory_xact_lock blocks until peers release; the lock auto-releases
  //    at COMMIT/ROLLBACK so we don't track it ourselves.
  try {
    await pg.begin(async (tx) => {
      const txPg = tx as TaggedSql
      await txPg`SELECT pg_advisory_xact_lock(${MIGRATION_LOCK_KEY})`

      const rows = (await txPg`
        SELECT version FROM manta_schema_versions WHERE name = 'framework'
      `) as { version: number }[]
      const current = rows[0]?.version ?? 0

      if (current >= FRAMEWORK_SCHEMA_VERSION) {
        logger.info(`[manta-schema] framework v${current} — up to date`)
        return
      }

      logger.info(`[manta-schema] migrating framework v${current} → v${FRAMEWORK_SCHEMA_VERSION}`)
      await applyFrameworkDdl(txPg)
      await txPg`
        INSERT INTO manta_schema_versions (name, version)
        VALUES ('framework', ${FRAMEWORK_SCHEMA_VERSION})
        ON CONFLICT (name) DO UPDATE
          SET version = EXCLUDED.version,
              applied_at = NOW()
      `
      logger.info(`[manta-schema] framework v${FRAMEWORK_SCHEMA_VERSION} applied`)
    })
  } catch (err) {
    logger.error('Failed to migrate framework schema', err)
    throw err
  }
}

/**
 * Framework DDL — applied in version order. All statements idempotent
 * (IF NOT EXISTS / IF EXISTS) so a partial failure + retry remains safe.
 */
async function applyFrameworkDdl(pg: TaggedSql): Promise<void> {
  // ── Legacy cleanup (WP-F05) ─────────────────────────────────────
  // `workflow_executions` was superseded by `workflow_runs` in the Workflow
  // Progress Tracking epic (2026-04-17). Drop it if it lingers from an old boot.
  await pg`DROP TABLE IF EXISTS workflow_executions`
  // ────────────────────────────────────────────────────────────────
  await pg`CREATE TABLE IF NOT EXISTS stats (key TEXT PRIMARY KEY, value INTEGER NOT NULL DEFAULT 0)`
  await pg`CREATE TABLE IF NOT EXISTS workflow_checkpoints (id SERIAL PRIMARY KEY, transaction_id TEXT NOT NULL, step_id TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', data JSONB DEFAULT '{}', error TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(transaction_id, step_id))`
  await pg`CREATE INDEX IF NOT EXISTS idx_wf_checkpoints_tx ON workflow_checkpoints(transaction_id)`
  await pg`CREATE TABLE IF NOT EXISTS workflow_runs (id TEXT PRIMARY KEY, command_name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', steps JSONB NOT NULL DEFAULT '[]', input JSONB NOT NULL DEFAULT '{}', output JSONB, error JSONB, started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), completed_at TIMESTAMPTZ, cancel_requested_at TIMESTAMPTZ, heartbeat_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`
  await pg`CREATE INDEX IF NOT EXISTS idx_workflow_runs_cmd_started ON workflow_runs(command_name, started_at DESC)`
  // WP-F04 — heartbeat column added for existing deployments (migration-safe).
  await pg`ALTER TABLE workflow_runs ADD COLUMN IF NOT EXISTS heartbeat_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`
  // WP-F04 — partial index covering only orphan candidates (status='running').
  await pg`CREATE INDEX IF NOT EXISTS idx_workflow_runs_heartbeat ON workflow_runs(status, heartbeat_at) WHERE status = 'running'`
  await pg`CREATE TABLE IF NOT EXISTS workflow_progress (run_id TEXT PRIMARY KEY, step_name TEXT NOT NULL, current INTEGER NOT NULL, total INTEGER, message TEXT, at_ms BIGINT NOT NULL)`
  await pg`CREATE TABLE IF NOT EXISTS events (id SERIAL PRIMARY KEY, event_name TEXT NOT NULL, data JSONB DEFAULT '{}', metadata JSONB DEFAULT '{}', status TEXT NOT NULL DEFAULT 'pending', attempts INTEGER DEFAULT 0, max_attempts INTEGER DEFAULT 3, last_error TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), processed_at TIMESTAMPTZ)`
  await pg`CREATE TABLE IF NOT EXISTS job_executions (id SERIAL PRIMARY KEY, job_name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'running', result JSONB, error TEXT, duration_ms INTEGER, started_at TIMESTAMPTZ DEFAULT NOW(), completed_at TIMESTAMPTZ)`
  await pg`CREATE TABLE IF NOT EXISTS cron_heartbeats (id SERIAL PRIMARY KEY, job_name TEXT NOT NULL, message TEXT, executed_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`
}

/** DML type → SQL type mapping */
export const DML_TO_SQL: Record<string, string> = {
  id: 'TEXT PRIMARY KEY',
  text: 'TEXT',
  number: 'INTEGER',
  boolean: 'BOOLEAN',
  float: 'REAL',
  bigNumber: 'NUMERIC',
  serial: 'SERIAL',
  dateTime: 'TIMESTAMPTZ',
  json: 'JSONB',
  enum: 'TEXT',
  array: 'JSONB',
}

/**
 * Auto-create tables from discovered DML entities + links.
 * No hardcoded application tables — everything comes from defineModel() and defineLink().
 */
export async function ensureEntityTables(
  sql: unknown,
  entities: Array<{ name: string; schema: Record<string, unknown> }>,
  links: Array<{ tableName: string; leftFk: string; rightFk: string; extraColumns?: Record<string, unknown> }>,
  logger: ILoggerPort,
): Promise<void> {
  const pg = sql as PostgresSql

  for (const entity of entities) {
    const _tableName = entityToTableKey(entity.name)
      .replace(/([A-Z])/g, '_$1')
      .toLowerCase()
      .replace(/^_/, '')
    // Convert camelCase to snake_case for table name
    const snakeTable = entity.name.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase()
    const finalTable =
      snakeTable.endsWith('s') || snakeTable.endsWith('x') || snakeTable.endsWith('ch') || snakeTable.endsWith('sh')
        ? `${snakeTable}es`
        : snakeTable.endsWith('y') && !/[aeiou]y$/i.test(snakeTable)
          ? `${snakeTable.slice(0, -1)}ies`
          : `${snakeTable}s`

    const columns: string[] = ['id TEXT PRIMARY KEY']

    for (const [fieldName, value] of Object.entries(entity.schema)) {
      const v = value as Record<string, unknown>
      if (v?.__dmlRelation === true) continue
      if (typeof v?.parse !== 'function') continue

      const meta = (v.parse as (name: string) => Record<string, unknown>)(fieldName)
      if (meta.computed) continue

      const dataType = meta.dataType as { name: string } | undefined
      const sqlType = DML_TO_SQL[dataType?.name ?? ''] ?? 'TEXT'
      const notNull = !meta.nullable ? ' NOT NULL' : ''
      let defaultClause = ''
      if (meta.defaultValue !== undefined) {
        if (typeof meta.defaultValue === 'string') {
          const escaped = meta.defaultValue.replace(/'/g, "''")
          defaultClause = ` DEFAULT '${escaped}'`
        } else {
          defaultClause = ` DEFAULT ${meta.defaultValue}`
        }
      }
      const uniqueClause = meta.unique ? ' UNIQUE' : ''
      columns.push(`${fieldName} ${sqlType}${notNull}${defaultClause}${uniqueClause}`)
    }

    // Implicit columns — only add if not already defined by the schema
    const definedColumns = new Set(columns.map((c) => c.split(' ')[0].toLowerCase()))
    if (!definedColumns.has('metadata')) columns.push("metadata JSONB DEFAULT '{}'")
    if (!definedColumns.has('created_at')) columns.push('created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()')
    if (!definedColumns.has('updated_at')) columns.push('updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()')
    if (!definedColumns.has('deleted_at')) columns.push('deleted_at TIMESTAMPTZ')

    const ddl = `CREATE TABLE IF NOT EXISTS ${finalTable} (${columns.join(', ')})`
    try {
      await (pg as { unsafe: (query: string) => Promise<unknown[]> }).unsafe(ddl)
      logger.info(`  Table: ${finalTable} (auto-generated from ${entity.name})`)
    } catch (err) {
      // Table may already exist with different schema — skip
      logger.warn(`  Table ${finalTable}: ${(err as Error).message}`)
    }

    // Add missing columns to existing tables (ALTER TABLE ADD COLUMN IF NOT EXISTS)
    for (const col of columns) {
      if (col.startsWith('id ')) continue // skip primary key
      const colName = col.split(' ')[0]
      const colDef = col.slice(colName.length + 1)
      try {
        await (pg as { unsafe: (query: string) => Promise<unknown[]> }).unsafe(
          `ALTER TABLE ${finalTable} ADD COLUMN IF NOT EXISTS ${colName} ${colDef}`,
        )
      } catch {
        // Column already exists or other non-critical error — skip
      }
    }
  }

  // Create link pivot tables
  for (const link of links) {
    // Build extra column DDL fragments from defineLink() extraColumns
    const extraColDefs: string[] = []
    if (link.extraColumns) {
      for (const [fieldName, fieldValue] of Object.entries(link.extraColumns)) {
        const v = fieldValue as Record<string, unknown>
        if (typeof v?.parse === 'function') {
          const meta = (v.parse as (name: string) => Record<string, unknown>)(fieldName)
          const dataType = meta.dataType as { name: string } | undefined
          const sqlType = DML_TO_SQL[dataType?.name ?? ''] ?? 'TEXT'
          const notNull = !meta.nullable ? ' NOT NULL' : ''
          let defaultClause = ''
          if (meta.defaultValue !== undefined) {
            if (typeof meta.defaultValue === 'string') {
              const escaped = (meta.defaultValue as string).replace(/'/g, "''")
              defaultClause = ` DEFAULT '${escaped}'`
            } else {
              defaultClause = ` DEFAULT ${meta.defaultValue}`
            }
          }
          extraColDefs.push(`${fieldName} ${sqlType}${notNull}${defaultClause}`)
        } else {
          extraColDefs.push(`${fieldName} TEXT`)
        }
      }
    }

    const extraColSql = extraColDefs.length > 0 ? `, ${extraColDefs.join(', ')}` : ''
    const ddl = `CREATE TABLE IF NOT EXISTS ${link.tableName} (id TEXT PRIMARY KEY, ${link.leftFk} TEXT NOT NULL, ${link.rightFk} TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW(), deleted_at TIMESTAMPTZ${extraColSql})`
    try {
      await (pg as { unsafe: (query: string) => Promise<unknown[]> }).unsafe(ddl)
      logger.info(`  Link table: ${link.tableName} (auto-generated)`)
    } catch (err) {
      logger.warn(`  Link table ${link.tableName}: ${(err as Error).message}`)
    }

    // Add missing extra columns to existing link tables (ALTER TABLE ADD COLUMN IF NOT EXISTS)
    for (const colDef of extraColDefs) {
      const colName = colDef.split(' ')[0]
      const colRest = colDef.slice(colName.length + 1)
      try {
        await (pg as { unsafe: (query: string) => Promise<unknown[]> }).unsafe(
          `ALTER TABLE ${link.tableName} ADD COLUMN IF NOT EXISTS ${colName} ${colRest}`,
        )
      } catch {
        // Column already exists or other non-critical error — skip
      }
    }
  }
}
