// bootstrap-context.ts — Shared context object threaded through all bootstrap phases.
// Replaces most `any` fields with concrete types from @manta/core and the adapters.

import type { generateLinkPgTable, generatePgTableFromDml } from '@manta/adapter-database-pg'
import type { H3Adapter } from '@manta/adapter-h3'
import type {
  CommandGraphDefinition,
  CommandRegistry,
  ContextRegistry,
  ILoggerPort,
  MantaApp,
  MantaAppBuilder,
  QueryGraphExtensionDefinition,
  QueryRegistry,
  UserDefinition,
} from '@manta/core'
import type { AuthModuleService } from '@manta/core/auth'
import type { IDatabasePort, IQueuePort, IRepositoryFactory } from '@manta/core/ports'

// Re-export alias — `IQueuePort` lives in core/ports and is referenced
// below via the bootstrap-context's workflow continuation wiring.
type IQueuePortRef = IQueuePort

import type { DiscoveredResources } from '../resource-loader'
import type { LoadedConfig } from '../types'
import type { BootstrapOptions } from './bootstrap-app'
import type { DmlEntityLike } from './bootstrap-helpers'

export type AppRef = { current: MantaApp | null }

/** A resource entry that the bootstrap loader cannot fully type at runtime — the
 * underlying definition comes from user code that is imported dynamically. */
// biome-ignore lint/suspicious/noExplicitAny: heterogeneous user-code definition (entity command / agent / link etc.)
type OpaqueDefinition = Record<string, any>

export interface BootstrapContext {
  // Inputs
  readonly cwd: string
  readonly mode: 'dev' | 'prod'
  readonly verbose: boolean
  readonly doImport: (path: string) => Promise<Record<string, unknown>>
  readonly config: LoadedConfig
  readonly options: BootstrapOptions

  // Phase 1: Infra
  logger: ILoggerPort
  db: IDatabasePort
  infraMap: Map<string, unknown>
  repoFactory: IRepositoryFactory
  builder: MantaAppBuilder
  generatePgTableFromDml: typeof generatePgTableFromDml
  generateLinkPgTable: typeof generateLinkPgTable

  // Phase 2: Discovery
  resources: DiscoveredResources
  resolvedPlugins: Array<{ name: string; rootDir: string }>

  // Phase 3: Assembly (all the registries)
  generatedTables: Map<string, unknown>
  entityRegistry: Map<string, DmlEntityLike>
  loadedLinks: Array<Record<string, unknown>>
  /** Entity commands auto-generated by generateEntityCommands — shape varies per op. */
  entityCommandRegistry: Map<string, OpaqueDefinition>
  explicitCommandNames: Set<string>
  commandGraphDefs: Map<string, CommandGraphDefinition>
  queryRegistry: QueryRegistry
  queryGraphDefs: Map<string, unknown>
  queryExtensions: QueryGraphExtensionDefinition[]
  userDefinitions: Array<{ contextName: string; def: UserDefinition }>
  moduleScopedCommandNames: string[]
  cmdRegistry: CommandRegistry | null
  /**
   * Queue adapter used for workflow continuations (ctx.yield). Set by
   * wire-commands so the resume route can share the same instance.
   */
  workflowQueue?: IQueuePortRef
  /**
   * Builder fn `(runId) => url` for the queue's resume POST target. Must
   * produce a URL the queue adapter can reach (= public internet URL on
   * Vercel / serverless). Set by wire-commands.
   */
  workflowResumeEndpoint?: (runId: string) => string
  /**
   * Wall-clock budget (ms) steps get before they must `ctx.yield(state)`.
   * Defaults to 7s on Vercel, undefined (unbounded) on long-running Node.
   */
  workflowStepBudgetMs?: number
  /** Agents are user-defined step definitions — shape is intentionally open. */
  agentRegistry: Map<string, OpaqueDefinition>

  // Phase 5: Wiring
  adapter: H3Adapter
  authService: AuthModuleService
  jwtSecret: string
  contextRegistry: ContextRegistry
}
