// bootstrap-helpers.ts — Pure helper functions extracted from bootstrap-app.ts
// These functions are standalone (explicit params, no closures over bootstrap locals).

import type { ILoggerPort } from '@manta/core'
import type { IRepositoryFactory } from '@manta/core/ports'
import type postgres from 'postgres'

// ── DML entity type guard ─────────────────────────────────────────

export interface DmlEntityLike {
  name: string
  schema: Record<string, unknown>
  getOptions?: () => Record<string, unknown>
}

export function isDmlEntity(value: unknown): value is DmlEntityLike {
  return (
    typeof value === 'object' &&
    value !== null &&
    'name' in value &&
    'schema' in value &&
    typeof (value as Record<string, unknown>).name === 'string'
  )
}

// ── Service class introspection type guard ────────────────────────

export function hasModelObjects(
  cls: unknown,
): cls is (new (...args: unknown[]) => unknown) & { $modelObjects: Record<string, unknown> } {
  return typeof cls === 'function' && '$modelObjects' in cls
}

// ── Raw SQL with unsafe() ─────────────────────────────────────────

type PostgresSql = ReturnType<typeof postgres>

// ====================================================================
// Helpers (internal)
// ====================================================================

/**
 * Entity name → table export name convention.
 * Product → products, InventoryItem → inventoryItems
 */
export function entityToTableKey(entityName: string): string {
  const name = entityName.charAt(0).toLowerCase() + entityName.slice(1)
  if (name.endsWith('s') || name.endsWith('x') || name.endsWith('ch') || name.endsWith('sh')) return `${name}es`
  if (name.endsWith('y') && !/[aeiou]y$/i.test(name)) return `${name.slice(0, -1)}ies`
  return `${name}s`
}

export function tryInstantiateService(
  ServiceClass: new (...args: unknown[]) => unknown,
  infraMap: Map<string, unknown>,
  repoFactory: IRepositoryFactory,
): unknown | null {
  try {
    // Detect createService() classes — they have $modelObjects set by the framework
    const modelObjects = hasModelObjects(ServiceClass) ? ServiceClass.$modelObjects : undefined
    if (modelObjects) {
      const firstEntry = Object.entries(modelObjects)[0]
      if (firstEntry) {
        const entityName = isDmlEntity(firstEntry[1]) ? firstEntry[1].name : firstEntry[0]
        try {
          const repo = repoFactory.createRepository(entityToTableKey(entityName))
          return new ServiceClass({ baseRepository: repo })
        } catch {
          // Table not registered — fall through to other instantiation strategies
        }
      }
    }

    if (ServiceClass.length === 0) return new ServiceClass()
    const name = ServiceClass.name || ''
    if (name === 'FileService' || name === 'FileModuleService') {
      const file = infraMap.get('IFilePort')
      if (file) return new ServiceClass(file)
    }
    const portKeys = ['IFilePort', 'IDatabasePort', 'ILoggerPort', 'IEventBusPort', 'ICachePort']
    for (const key of portKeys) {
      const port = infraMap.get(key)
      if (port) {
        try {
          return new ServiceClass(port)
        } catch {}
      }
    }
    return null
  } catch {
    return null
  }
}

/**
 * Generate .manta/types.ts — module augmentation for typed step proxy.
 * Scans discovered modules, finds DML entities, writes the type file.
 */
export async function generateMantaTypes(
  cwd: string,
  modules: Array<{ name: string; dirName?: string; entities: Array<{ name: string; modelPath: string }> }>,
  doImport: (path: string) => Promise<Record<string, unknown>>,
  logger: ILoggerPort,
): Promise<void> {
  const { existsSync, mkdirSync, writeFileSync } = await import('node:fs')
  const { resolve, relative } = await import('node:path')

  const mantaDir = resolve(cwd, '.manta', 'types')
  if (!existsSync(mantaDir)) mkdirSync(mantaDir, { recursive: true })

  // Collect entity info: module name → { entityExportName, entityName, relativePath }
  const entries: Array<{ moduleName: string; entityExportName: string; entityName: string; modulePath: string }> = []

  for (const modInfo of modules) {
    for (const entity of modInfo.entities) {
      try {
        const mod = await doImport(entity.modelPath)
        for (const [exportName, value] of Object.entries(mod)) {
          if (isDmlEntity(value) && typeof value.getOptions === 'function') {
            entries.push({
              moduleName: modInfo.name,
              entityExportName: exportName,
              entityName: value.name,
              modulePath: entity.modelPath,
            })
          }
        }
      } catch {
        // Entity model may not export DML entities
      }
    }
  }

  if (entries.length === 0) return

  // Build the type file
  const lines: string[] = [
    '// Auto-generated by manta dev — DO NOT EDIT',
    '// This file provides typed step.product.create(), step.inventoryItem.create(), etc.',
    '// Regenerated on every boot when modules change.',
    '',
  ]

  // Import statements
  for (const entry of entries) {
    const relPath = relative(mantaDir, entry.modulePath).replace(/\.ts$/, '')
    lines.push(`import type { ${entry.entityExportName} } from '${relPath}'`)
  }

  lines.push('')
  lines.push("declare module '@manta/core' {")
  lines.push('  interface MantaEntities {')
  for (const entry of entries) {
    lines.push(`    ${entry.moduleName}: typeof ${entry.entityExportName}`)
  }
  lines.push('  }')
  lines.push('}')
  lines.push('')

  const typesPath = resolve(mantaDir, 'types.ts')
  writeFileSync(typesPath, lines.join('\n'))
  logger.info(`[codegen] .manta/types.ts generated (${entries.length} entities)`)
}

// ── Framework schema migration system ─────────────────────────────────
//
// Bump FRAMEWORK_SCHEMA_VERSION whenever `applyFrameworkDdl` changes in a way
// that requires an existing deployment to re-run DDL. Stored in the
// `manta_schema_versions` table; gates whether migrations run at boot.
// Bumping it triggers one (and only one) re-application per deployment.
export const FRAMEWORK_SCHEMA_VERSION = 1

// Hard cap on how long migrations may run at boot. Cold-start budgets on
// serverless (Vercel) are tight — we never want framework schema work to
// be the reason a lambda times out. Caller receives a timeout error after
// this window and can decide whether to continue booting.
const MIGRATION_TIMEOUT_MS = 8_000

// Advisory lock key — arbitrary int64 unique to Manta. `pg_advisory_xact_lock`
// serializes parallel boots so exactly one process applies migrations at a
// time. Auto-released on COMMIT/ROLLBACK.
const MIGRATION_LOCK_KEY = 0x4d414e544101n // 'MANTA' + version byte

type TaggedSql = (strings: TemplateStringsArray, ...values: unknown[]) => Promise<unknown>
type BeginFn = (cb: (tx: TaggedSql & { begin?: BeginFn }) => Promise<unknown>) => Promise<unknown>
type TaggedSqlWithBegin = TaggedSql & { begin: BeginFn }

function withTimeout<T>(p: Promise<T>, ms: number, label: string): Promise<T> {
  let timer: ReturnType<typeof setTimeout> | undefined
  const timeout = new Promise<never>((_resolve, reject) => {
    timer = setTimeout(() => reject(new Error(`${label} timed out after ${ms}ms`)), ms)
  })
  return Promise.race([p, timeout]).finally(() => {
    if (timer) clearTimeout(timer)
  }) as Promise<T>
}

/**
 * Ensure Manta's framework-internal schema is at FRAMEWORK_SCHEMA_VERSION.
 *
 * Safe to call unconditionally on every boot (dev, prod, serverless). A
 * Postgres advisory transaction lock serializes concurrent boots, and a
 * version table means only the first boot of a new deploy runs DDL;
 * subsequent boots read a single row and return.
 *
 * The whole operation is bounded by `MIGRATION_TIMEOUT_MS` so a misbehaving
 * pooler or lock never blocks a serverless cold start indefinitely. The
 * caller is expected to try/catch around this call and continue booting on
 * error — framework-dependent endpoints will fail loudly on first access,
 * which is strictly better than taking the whole app down.
 *
 * Framework tables are Manta-owned; the user never writes to them. That's
 * why we manage them here rather than via `manta db:*`, which is the
 * app-level migration surface.
 */
export async function ensureFrameworkSchema(sql: unknown, logger: ILoggerPort): Promise<void> {
  const pg = sql as TaggedSqlWithBegin

  // 1. Meta table — CREATE IF NOT EXISTS is atomic in Postgres; safe if
  //    multiple boots race here before the lock is acquired.
  await withTimeout(
    pg`
      CREATE TABLE IF NOT EXISTS manta_schema_versions (
        name TEXT PRIMARY KEY,
        version INTEGER NOT NULL,
        applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    ` as Promise<unknown>,
    MIGRATION_TIMEOUT_MS,
    '[manta-schema] meta table',
  )

  // 2. Acquire lock + version-gate + apply DDL in a single transaction.
  //    pg_advisory_xact_lock blocks until peers release; the lock auto-releases
  //    at COMMIT/ROLLBACK so we don't track it ourselves.
  await withTimeout(
    pg.begin(async (tx) => {
      const txPg = tx as TaggedSql
      await txPg`SELECT pg_advisory_xact_lock(${MIGRATION_LOCK_KEY})`

      const rows = (await txPg`
        SELECT version FROM manta_schema_versions WHERE name = 'framework'
      `) as { version: number }[]
      const current = rows[0]?.version ?? 0

      if (current >= FRAMEWORK_SCHEMA_VERSION) {
        logger.info(`[manta-schema] framework v${current} — up to date`)
        return
      }

      logger.info(`[manta-schema] migrating framework v${current} → v${FRAMEWORK_SCHEMA_VERSION}`)
      await applyFrameworkDdl(txPg)
      await txPg`
        INSERT INTO manta_schema_versions (name, version)
        VALUES ('framework', ${FRAMEWORK_SCHEMA_VERSION})
        ON CONFLICT (name) DO UPDATE
          SET version = EXCLUDED.version,
              applied_at = NOW()
      `
      logger.info(`[manta-schema] framework v${FRAMEWORK_SCHEMA_VERSION} applied`)
    }) as Promise<unknown>,
    MIGRATION_TIMEOUT_MS,
    '[manta-schema] migration transaction',
  )
}

/**
 * Framework DDL — applied in version order. All statements idempotent
 * (IF NOT EXISTS / IF EXISTS) so a partial failure + retry remains safe.
 */
async function applyFrameworkDdl(pg: TaggedSql): Promise<void> {
  await pg`CREATE TABLE IF NOT EXISTS stats (key TEXT PRIMARY KEY, value INTEGER NOT NULL DEFAULT 0)`
  await pg`CREATE TABLE IF NOT EXISTS workflow_checkpoints (id SERIAL PRIMARY KEY, transaction_id TEXT NOT NULL, step_id TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending', data JSONB DEFAULT '{}', error TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW(), UNIQUE(transaction_id, step_id))`
  await pg`CREATE INDEX IF NOT EXISTS idx_wf_checkpoints_tx ON workflow_checkpoints(transaction_id)`
  await pg`CREATE TABLE IF NOT EXISTS workflow_executions (transaction_id TEXT PRIMARY KEY, workflow_name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'running', input JSONB DEFAULT '{}', result JSONB, error TEXT, started_at TIMESTAMPTZ DEFAULT NOW(), completed_at TIMESTAMPTZ)`
  await pg`CREATE TABLE IF NOT EXISTS events (id SERIAL PRIMARY KEY, event_name TEXT NOT NULL, data JSONB DEFAULT '{}', metadata JSONB DEFAULT '{}', status TEXT NOT NULL DEFAULT 'pending', attempts INTEGER DEFAULT 0, max_attempts INTEGER DEFAULT 3, last_error TEXT, created_at TIMESTAMPTZ DEFAULT NOW(), processed_at TIMESTAMPTZ)`
  await pg`CREATE TABLE IF NOT EXISTS job_executions (id SERIAL PRIMARY KEY, job_name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'running', result JSONB, error TEXT, duration_ms INTEGER, started_at TIMESTAMPTZ DEFAULT NOW(), completed_at TIMESTAMPTZ)`
  await pg`CREATE TABLE IF NOT EXISTS cron_heartbeats (id SERIAL PRIMARY KEY, job_name TEXT NOT NULL, message TEXT, executed_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`
}

/**
 * @deprecated Use `ensureFrameworkSchema` instead. Kept as an alias so
 *             existing call sites (init-infra, tests, the Neon adapter
 *             comment) don't break.
 */
export async function ensureFrameworkTables(sql: unknown, logger: ILoggerPort): Promise<void> {
  await ensureFrameworkSchema(sql, logger)
}

/** DML type → SQL type mapping */
export const DML_TO_SQL: Record<string, string> = {
  id: 'TEXT PRIMARY KEY',
  text: 'TEXT',
  number: 'INTEGER',
  boolean: 'BOOLEAN',
  float: 'REAL',
  bigNumber: 'NUMERIC',
  serial: 'SERIAL',
  dateTime: 'TIMESTAMPTZ',
  json: 'JSONB',
  enum: 'TEXT',
  array: 'JSONB',
}

/**
 * Auto-create tables from discovered DML entities + links.
 * No hardcoded application tables — everything comes from defineModel() and defineLink().
 */
export async function ensureEntityTables(
  sql: unknown,
  entities: Array<{ name: string; schema: Record<string, unknown> }>,
  links: Array<{ tableName: string; leftFk: string; rightFk: string; extraColumns?: Record<string, unknown> }>,
  logger: ILoggerPort,
): Promise<void> {
  const pg = sql as PostgresSql

  for (const entity of entities) {
    const _tableName = entityToTableKey(entity.name)
      .replace(/([A-Z])/g, '_$1')
      .toLowerCase()
      .replace(/^_/, '')
    // Convert camelCase to snake_case for table name
    const snakeTable = entity.name.replace(/([a-z])([A-Z])/g, '$1_$2').toLowerCase()
    const finalTable =
      snakeTable.endsWith('s') || snakeTable.endsWith('x') || snakeTable.endsWith('ch') || snakeTable.endsWith('sh')
        ? `${snakeTable}es`
        : snakeTable.endsWith('y') && !/[aeiou]y$/i.test(snakeTable)
          ? `${snakeTable.slice(0, -1)}ies`
          : `${snakeTable}s`

    const columns: string[] = ['id TEXT PRIMARY KEY']

    for (const [fieldName, value] of Object.entries(entity.schema)) {
      const v = value as Record<string, unknown>
      if (v?.__dmlRelation === true) continue
      if (typeof v?.parse !== 'function') continue

      const meta = (v.parse as (name: string) => Record<string, unknown>)(fieldName)
      if (meta.computed) continue

      const dataType = meta.dataType as { name: string } | undefined
      const sqlType = DML_TO_SQL[dataType?.name ?? ''] ?? 'TEXT'
      const notNull = !meta.nullable ? ' NOT NULL' : ''
      let defaultClause = ''
      if (meta.defaultValue !== undefined) {
        if (typeof meta.defaultValue === 'string') {
          const escaped = meta.defaultValue.replace(/'/g, "''")
          defaultClause = ` DEFAULT '${escaped}'`
        } else {
          defaultClause = ` DEFAULT ${meta.defaultValue}`
        }
      }
      const uniqueClause = meta.unique ? ' UNIQUE' : ''
      columns.push(`${fieldName} ${sqlType}${notNull}${defaultClause}${uniqueClause}`)
    }

    // Implicit columns — only add if not already defined by the schema
    const definedColumns = new Set(columns.map((c) => c.split(' ')[0].toLowerCase()))
    if (!definedColumns.has('metadata')) columns.push("metadata JSONB DEFAULT '{}'")
    if (!definedColumns.has('created_at')) columns.push('created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()')
    if (!definedColumns.has('updated_at')) columns.push('updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()')
    if (!definedColumns.has('deleted_at')) columns.push('deleted_at TIMESTAMPTZ')

    const ddl = `CREATE TABLE IF NOT EXISTS ${finalTable} (${columns.join(', ')})`
    try {
      await (pg as { unsafe: (query: string) => Promise<unknown[]> }).unsafe(ddl)
      logger.info(`  Table: ${finalTable} (auto-generated from ${entity.name})`)
    } catch (err) {
      // Table may already exist with different schema — skip
      logger.warn(`  Table ${finalTable}: ${(err as Error).message}`)
    }

    // Add missing columns to existing tables (ALTER TABLE ADD COLUMN IF NOT EXISTS)
    for (const col of columns) {
      if (col.startsWith('id ')) continue // skip primary key
      const colName = col.split(' ')[0]
      const colDef = col.slice(colName.length + 1)
      try {
        await (pg as { unsafe: (query: string) => Promise<unknown[]> }).unsafe(
          `ALTER TABLE ${finalTable} ADD COLUMN IF NOT EXISTS ${colName} ${colDef}`,
        )
      } catch {
        // Column already exists or other non-critical error — skip
      }
    }
  }

  // Create link pivot tables
  for (const link of links) {
    // Build extra column DDL fragments from defineLink() extraColumns
    const extraColDefs: string[] = []
    if (link.extraColumns) {
      for (const [fieldName, fieldValue] of Object.entries(link.extraColumns)) {
        const v = fieldValue as Record<string, unknown>
        if (typeof v?.parse === 'function') {
          const meta = (v.parse as (name: string) => Record<string, unknown>)(fieldName)
          const dataType = meta.dataType as { name: string } | undefined
          const sqlType = DML_TO_SQL[dataType?.name ?? ''] ?? 'TEXT'
          const notNull = !meta.nullable ? ' NOT NULL' : ''
          let defaultClause = ''
          if (meta.defaultValue !== undefined) {
            if (typeof meta.defaultValue === 'string') {
              const escaped = (meta.defaultValue as string).replace(/'/g, "''")
              defaultClause = ` DEFAULT '${escaped}'`
            } else {
              defaultClause = ` DEFAULT ${meta.defaultValue}`
            }
          }
          extraColDefs.push(`${fieldName} ${sqlType}${notNull}${defaultClause}`)
        } else {
          extraColDefs.push(`${fieldName} TEXT`)
        }
      }
    }

    const extraColSql = extraColDefs.length > 0 ? `, ${extraColDefs.join(', ')}` : ''
    const ddl = `CREATE TABLE IF NOT EXISTS ${link.tableName} (id TEXT PRIMARY KEY, ${link.leftFk} TEXT NOT NULL, ${link.rightFk} TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW(), deleted_at TIMESTAMPTZ${extraColSql})`
    try {
      await (pg as { unsafe: (query: string) => Promise<unknown[]> }).unsafe(ddl)
      logger.info(`  Link table: ${link.tableName} (auto-generated)`)
    } catch (err) {
      logger.warn(`  Link table ${link.tableName}: ${(err as Error).message}`)
    }

    // Add missing extra columns to existing link tables (ALTER TABLE ADD COLUMN IF NOT EXISTS)
    for (const colDef of extraColDefs) {
      const colName = colDef.split(' ')[0]
      const colRest = colDef.slice(colName.length + 1)
      try {
        await (pg as { unsafe: (query: string) => Promise<unknown[]> }).unsafe(
          `ALTER TABLE ${link.tableName} ADD COLUMN IF NOT EXISTS ${colName} ${colRest}`,
        )
      } catch {
        // Column already exists or other non-critical error — skip
      }
    }
  }
}
