packages:
  - 'demo/commerce'

onlyBuiltDependencies:
  - '@medusajs/telemetry'
  - '@swc/core'
  - esbuild
  - msgpackr-extract
  - protobufjs
  - sharp
  - simple-git-hooks
allowBuilds:
  '@medusajs/telemetry': true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  simple-git-hooks: true
minimumReleaseAgeExclude:
  - '@mantajs/adapter-cache-upstash@0.2.0-beta.2'
  - '@mantajs/adapter-database-neon@0.2.0-beta.2'
  - '@mantajs/adapter-database-pg@0.2.0-beta.2'
  - '@mantajs/adapter-eventbus-upstash@0.2.0-beta.2'
  - '@mantajs/adapter-file-vercel-blob@0.2.0-beta.2'
  - '@mantajs/adapter-h3@0.2.0-beta.2'
  - '@mantajs/adapter-jobs-vercel-cron@0.2.0-beta.2'
  - '@mantajs/adapter-locking-neon@0.2.0-beta.2'
  - '@mantajs/adapter-logger-pino@0.2.0-beta.2'
  - '@mantajs/adapter-notification-resend@0.2.0-beta.2'
  - '@mantajs/adapter-queue-qstash@0.2.0-beta.2'
  - '@mantajs/cli@0.2.0-beta.2'
  - '@mantajs/core@0.2.0-beta.2'
  - '@mantajs/dashboard@0.2.0-beta.2'
  - '@mantajs/host-nitro@0.2.0-beta.2'
  - '@mantajs/plugin-posthog-proxy@0.2.0-beta.2'
  - '@mantajs/sdk@0.2.0-beta.2'
  - '@mantajs/ui@0.2.0-beta.2'
