packages:
  - 'demo/commerce'

onlyBuiltDependencies:
  - '@medusajs/telemetry'
  - '@swc/core'
  - esbuild
  - msgpackr-extract
  - protobufjs
  - sharp
  - simple-git-hooks
allowBuilds:
  '@medusajs/telemetry': true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  simple-git-hooks: true
minimumReleaseAgeExclude:
  - '@mantajs/*'
patchedDependencies:
  '@mantajs/adapter-notification-resend@0.2.0-beta.12': patches/@mantajs__adapter-notification-resend@0.2.0-beta.12.patch
  '@mantajs/core@0.2.0-beta.12': patches/@mantajs__core@0.2.0-beta.12.patch
  '@mantajs/dashboard@0.2.0-beta.12': patches/@mantajs__dashboard@0.2.0-beta.12.patch
  '@mantajs/host-nitro@0.2.0-beta.12': patches/@mantajs__host-nitro@0.2.0-beta.12.patch
