// Auto-generated by @manta/host-nitro — DO NOT EDIT
// Catch-all: every request goes through the Manta H3 adapter.
// SPA fallback: if the adapter returns 404 for a SPA path (e.g. /admin/paniers),
// fetch index.html from the Vite dev server for client-side routing.

import { defineEventHandler, getRequestHeaders, getRequestURL, readRawBody } from 'h3'
import { getMantaAdapter } from '../manta-bootstrap'

export default defineEventHandler(async (event) => {
  const adapter = await getMantaAdapter()

  const url = getRequestURL(event)
  const method = event.method ?? 'GET'
  const headers = getRequestHeaders(event)

  let body: Uint8Array | undefined
  if (method !== 'GET' && method !== 'HEAD') {
    body = ((await readRawBody(event, false)) as Uint8Array | undefined) ?? undefined
  }

  const request = new Request(url.toString(), {
    method,
    headers,
    body: (body || undefined) as BodyInit | undefined,
  })
  const response = await adapter.handleRequest(request)

  // SPA fallback for dev mode: if the adapter returned 404 for a GET on a SPA path,
  // fetch the SPA index.html from Vite. In prod, Vercel rewrites handle this.
  if (response.status === 404 && method === 'GET') {
    const pathname = url.pathname
    const vitePort = process.env.__MANTA_VITE_PORT
    if (vitePort && pathname.startsWith('/admin') && !pathname.startsWith('/api/') && !pathname.match(/\.\w+$/)) {
      const viteRes = await fetch(`http://localhost:${vitePort}/admin/`)
      if (viteRes.ok) {
        return new Response(viteRes.body, {
          status: 200,
          headers: { 'content-type': 'text/html; charset=utf-8' },
        })
      }
    }
  }

  return response
})
