// Auto-generated by @manta/host-nitro — DO NOT EDIT
// Catch-all: every request goes through the Manta H3 adapter.
//
// Compatible with BOTH Node entry format (event.node.req exists) and
// Web entry format (Vercel — event.node is undefined, use event.headers/event.url).

import { defineEventHandler, getRequestHeaders, getRequestURL, readRawBody } from 'h3'
import { getMantaAdapter } from '../manta-bootstrap'

export default defineEventHandler(async (event) => {
  const adapter = await getMantaAdapter()

  // Build a standard Web Request from the H3 event.
  // Use H3 helpers (getRequestURL, getRequestHeaders) which work in BOTH
  // Node and Web entry formats — unlike event.node.req which is Node-only.
  const url = getRequestURL(event)
  const method = event.method ?? 'GET'
  const headers = getRequestHeaders(event)

  let body: Uint8Array | undefined
  if (method !== 'GET' && method !== 'HEAD') {
    body = ((await readRawBody(event, false)) as Uint8Array | undefined) ?? undefined
  }

  const request = new Request(url.toString(), {
    method,
    headers,
    body: (body || undefined) as BodyInit | undefined,
  })
  const response = await adapter.handleRequest(request)

  // Return the Web Response directly — Nitro V3 web entry format supports this.
  // In Node entry format, Nitro auto-converts the Response to a Node response.
  return response
})
