// Auto-generated by @manta/host-nitro — DO NOT EDIT
// Catch-all: every request goes through the Manta H3 adapter.

import { defineEventHandler, readRawBody } from 'h3'
import { getMantaAdapter } from '../manta-bootstrap'

export default defineEventHandler(async (event) => {
  const adapter = await getMantaAdapter()

  const url = new URL(event.path || '/', `http://${event.node.req.headers.host || 'localhost'}`)
  const method = event.method ?? 'GET'

  const headers: Record<string, string> = {}
  for (const [key, value] of Object.entries(event.node.req.headers)) {
    if (typeof value === 'string') headers[key] = value
  }

  let body: string | undefined
  if (method !== 'GET' && method !== 'HEAD') {
    body = (await readRawBody(event, 'utf8')) ?? undefined
  }

  const request = new Request(url.toString(), { method, headers, body: body || undefined })
  const response = await adapter.handleRequest(request)

  const res = event.node.res
  res.statusCode = response.status
  response.headers.forEach((value: string, key: string) => {
    res.setHeader(key, value)
  })

  // Stream the response body if it's a ReadableStream (e.g. AI chat)
  if (response.body && typeof response.body.getReader === 'function') {
    const reader = response.body.getReader()
    try {
      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        res.write(value)
      }
    } finally {
      res.end()
    }
  } else {
    const responseBody = await response.text()
    res.end(responseBody)
  }
})
