// generateEntityCommands — Auto-generate CRUD CommandDefinitions from a DML entity.
//
// For each entity in a module, generates atomic commands:
//   createProduct    → service.create + emit
//   updateProduct    → service.update + emit
//   deleteProduct    → service.delete + emit
//   retrieveProduct  → service.retrieve (read, no emit)
//   listProducts     → service.list (read, no emit)
//
// Names are camelCase for ergonomic `step.command.createProduct()` usage.
// The HTTP route handler converts kebab URLs to camelCase for lookup.

import { z } from 'zod'
import type { DmlEntity } from '../dml/entity'
import type { ResolvedLink } from '../link'
import { dmlToZod } from './dml-to-zod'
import type { CommandDefinition } from './types'

/**
 * Entity command operation type.
 * Used for filtering in defineCommandGraph (e.g. customer: ['create', 'update']).
 */
export type EntityCommandOperation = 'create' | 'update' | 'delete' | 'retrieve' | 'list' | 'link' | 'unlink'

/**
 * A generated entity command — a CommandDefinition augmented with module/entity metadata.
 */
export interface EntityCommand extends CommandDefinition {
  /** Module this command belongs to (e.g. 'catalog') */
  __module: string
  /** Entity this command operates on (e.g. 'Product') */
  __entity: string
  /** CRUD operation type */
  __operation: EntityCommandOperation
  /** Whether this is an auto-generated command (vs explicit) */
  __autoGenerated: true
}

function toKebab(name: string): string {
  return name
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase()
}

/** Convert any casing to camelCase: 'CustomerGroup' → 'customerGroup', 'customer_group' → 'customerGroup' */
function toCamel(name: string): string {
  // PascalCase → camelCase: 'CustomerGroup' → 'customerGroup'
  const kebab = toKebab(name)
  // kebab → camelCase: 'customer-group' → 'customerGroup'
  return kebab.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase())
}

function pluralize(name: string): string {
  if (name.endsWith('s') || name.endsWith('x') || name.endsWith('ch') || name.endsWith('sh')) {
    return `${name}es`
  }
  if (name.endsWith('y') && !/[aeiou]y$/i.test(name)) {
    return `${name.slice(0, -1)}ies`
  }
  return `${name}s`
}

/**
 * Generate CRUD commands for a single entity within a module.
 *
 * Command names use camelCase for ergonomic `step.command.createProduct()` usage.
 * The HTTP route handler converts kebab-case URLs to camelCase for lookup.
 *
 * @param moduleName - Module name (e.g. 'customer')
 * @param entity - DML entity definition
 * @returns Array of auto-generated EntityCommand definitions
 *
 * @example
 * ```typescript
 * const Customer = defineModel('Customer', { email: field.text(), name: field.text() })
 * const commands = generateEntityCommands('customer', Customer)
 * // → [
 * //   { name: 'createCustomer', ... },
 * //   { name: 'updateCustomer', ... },
 * //   { name: 'deleteCustomer', ... },
 * //   { name: 'retrieveCustomer', ... },
 * //   { name: 'listCustomers', ... },
 * // ]
 * // Usage: step.command.createCustomer({ email: '...' })
 * // HTTP:  POST /api/admin/command/create-customer
 * ```
 */
export function generateEntityCommands(moduleName: string, entity: DmlEntity): EntityCommand[] {
  const entityName = entity.name
  const entityCamel = toCamel(entityName)
  const entityLower = entityName.toLowerCase()
  const schemas = dmlToZod(entity)

  // Capitalize first letter for method names: 'customerGroup' → 'CustomerGroup'
  const cap = entityCamel.charAt(0).toUpperCase() + entityCamel.slice(1)
  const capPlural = pluralize(cap)

  const commands: EntityCommand[] = []

  // --- create ---
  commands.push({
    __type: 'command',
    __module: moduleName,
    __entity: entityName,
    __operation: 'create',
    __autoGenerated: true,
    name: `create${cap}`,
    description: `Create a new ${entityLower}`,
    input: schemas.create,
    workflow: async (input: unknown, ctx: unknown) => {
      // biome-ignore lint/suspicious/noExplicitAny: dynamic service resolution
      const app = (ctx as any).app
      const modules = app.modules as Record<string, Record<string, Function>>
      const service = modules[entityLower] ?? modules[moduleName]
      const result = await service[`create${pluralize(entityName)}`](input)

      const eventBus = app.infra?.eventBus
      if (eventBus) {
        const id = (result as Record<string, unknown>)?.id
        await eventBus.emit(`${entityLower}.created`, { id, ...(input as Record<string, unknown>) })
      }

      return result
    },
  })

  // --- update ---
  commands.push({
    __type: 'command',
    __module: moduleName,
    __entity: entityName,
    __operation: 'update',
    __autoGenerated: true,
    name: `update${cap}`,
    description: `Update an existing ${entityLower}`,
    input: schemas.update,
    workflow: async (input: unknown, ctx: unknown) => {
      const { id, ...data } = input as Record<string, unknown> & { id: string }
      // biome-ignore lint/suspicious/noExplicitAny: dynamic service resolution
      const app = (ctx as any).app
      const modules = app.modules as Record<string, Record<string, Function>>
      const service = modules[entityLower] ?? modules[moduleName]
      const result = await service[`update${pluralize(entityName)}`]({ id, ...data })

      const eventBus = app.infra?.eventBus
      if (eventBus) {
        await eventBus.emit(`${entityLower}.updated`, { id })
      }

      return result
    },
  })

  // --- delete ---
  commands.push({
    __type: 'command',
    __module: moduleName,
    __entity: entityName,
    __operation: 'delete',
    __autoGenerated: true,
    name: `delete${cap}`,
    description: `Delete a ${entityLower}`,
    input: schemas.delete,
    workflow: async (input: unknown, ctx: unknown) => {
      const { id } = input as { id: string }
      // biome-ignore lint/suspicious/noExplicitAny: dynamic service resolution
      const app = (ctx as any).app
      const modules = app.modules as Record<string, Record<string, Function>>
      const service = modules[entityLower] ?? modules[moduleName]
      await service[`delete${pluralize(entityName)}`](id)

      const eventBus = app.infra?.eventBus
      if (eventBus) {
        await eventBus.emit(`${entityLower}.deleted`, { id })
      }

      return { id, deleted: true }
    },
  })

  // --- retrieve ---
  commands.push({
    __type: 'command',
    __module: moduleName,
    __entity: entityName,
    __operation: 'retrieve',
    __autoGenerated: true,
    name: `retrieve${cap}`,
    description: `Retrieve a ${entityLower} by ID`,
    input: schemas.retrieve,
    workflow: async (input: unknown, ctx: unknown) => {
      const { id } = input as { id: string }
      // biome-ignore lint/suspicious/noExplicitAny: dynamic service resolution
      const app = (ctx as any).app
      const modules = app.modules as Record<string, Record<string, Function>>
      const service = modules[entityLower] ?? modules[moduleName]
      return service[`retrieve${entityName}`](id)
    },
  })

  // --- list ---
  commands.push({
    __type: 'command',
    __module: moduleName,
    __entity: entityName,
    __operation: 'list',
    __autoGenerated: true,
    name: `list${capPlural}`,
    description: `List ${entityLower} entities`,
    input: schemas.list,
    workflow: async (input: unknown, ctx: unknown) => {
      const { filters, limit, offset, order } = input as {
        filters?: Record<string, unknown>
        limit?: number
        offset?: number
        order?: Record<string, 'ASC' | 'DESC'>
      }
      // biome-ignore lint/suspicious/noExplicitAny: dynamic service resolution
      const app = (ctx as any).app
      const modules = app.modules as Record<string, Record<string, Function>>
      const service = modules[entityLower] ?? modules[moduleName]
      return service[`list${pluralize(entityName)}`](filters, { take: limit, skip: offset, order })
    },
  })

  return commands
}

/**
 * Generate entity commands for all entities in a module.
 */
export function generateModuleCommands(moduleName: string, models: Record<string, DmlEntity>): EntityCommand[] {
  const commands: EntityCommand[] = []
  for (const entity of Object.values(models)) {
    commands.push(...generateEntityCommands(moduleName, entity))
  }
  return commands
}

// ---------------------------------------------------------------------------
// Link commands — auto-generated from defineLink() definitions
// ---------------------------------------------------------------------------

/**
 * Generate link and unlink commands for a ResolvedLink.
 *
 * Names are camelCase for ergonomic usage: `step.command.linkCustomerCustomerGroup()`
 *
 * @example
 * ```typescript
 * // From: defineLink(many('customer'), many('customer_group'))
 * // Generates:
 * //   { name: 'linkCustomerCustomerGroup', ... }
 * //   { name: 'unlinkCustomerCustomerGroup', ... }
 * // Usage: step.command.linkCustomerCustomerGroup({ customer_id: '...', customer_group_id: '...' })
 * // HTTP:  POST /api/admin/command/link-customer-customer-group
 * ```
 */
export function generateLinkCommands(link: ResolvedLink): EntityCommand[] {
  const leftCamel = toCamel(link.leftEntity)
  const rightCamel = toCamel(link.rightEntity)
  const leftCap = leftCamel.charAt(0).toUpperCase() + leftCamel.slice(1)
  const rightCap = rightCamel.charAt(0).toUpperCase() + rightCamel.slice(1)
  const leftLower = link.leftEntity.toLowerCase()
  const rightLower = link.rightEntity.toLowerCase()

  const leftFk = link.leftFk
  const rightFk = link.rightFk

  const inputSchema = z.object({
    [leftFk]: z.string(),
    [rightFk]: z.string(),
  })

  const commands: EntityCommand[] = []

  // --- link ---
  commands.push({
    __type: 'command',
    __module: link.leftModule ?? leftLower,
    __entity: `${link.leftEntity}_${link.rightEntity}`,
    __operation: 'link',
    __autoGenerated: true,
    name: `link${leftCap}${rightCap}`,
    description: `Link a ${leftLower} to a ${rightLower}`,
    input: inputSchema,
    workflow: async (input: unknown, ctx: unknown) => {
      const data = input as Record<string, string>
      const leftId = data[leftFk]
      const rightId = data[rightFk]

      // biome-ignore lint/suspicious/noExplicitAny: dynamic app resolution
      const app = (ctx as any).app
      const db = (app.infra as Record<string, unknown>).db as {
        insert: (table: unknown) => { values: (v: unknown) => { onConflictDoNothing: () => Promise<unknown> } }
      }
      const tables = app.resolve('__generatedTables') as Map<string, unknown>
      const linkTable = tables.get(link.tableName)
      if (!linkTable) {
        throw new Error(`Link table "${link.tableName}" not found`)
      }

      await db
        .insert(linkTable)
        .values({
          id: `link_${leftId}_${rightId}`,
          [leftFk]: leftId,
          [rightFk]: rightId,
          created_at: new Date(),
          updated_at: new Date(),
        })
        .onConflictDoNothing()

      const eventBus = app.infra?.eventBus
      if (eventBus) {
        await eventBus.emit(`${leftLower}.${rightLower}.linked`, { [leftFk]: leftId, [rightFk]: rightId })
      }

      return { success: true }
    },
  })

  // --- unlink ---
  commands.push({
    __type: 'command',
    __module: link.leftModule ?? leftLower,
    __entity: `${link.leftEntity}_${link.rightEntity}`,
    __operation: 'unlink',
    __autoGenerated: true,
    name: `unlink${leftCap}${rightCap}`,
    description: `Unlink a ${leftLower} from a ${rightLower}`,
    input: inputSchema,
    workflow: async (input: unknown, ctx: unknown) => {
      const data = input as Record<string, string>
      const leftId = data[leftFk]
      const rightId = data[rightFk]

      // biome-ignore lint/suspicious/noExplicitAny: dynamic app resolution
      const app = (ctx as any).app
      const db = (app.infra as Record<string, unknown>).db as {
        delete: (table: unknown) => { where: (cond: unknown) => Promise<unknown> }
      }
      const tables = app.resolve('__generatedTables') as Map<string, unknown>
      const linkTable = tables.get(link.tableName)
      if (!linkTable) {
        throw new Error(`Link table "${link.tableName}" not found`)
      }

      // biome-ignore lint/suspicious/noExplicitAny: Drizzle dynamic column access
      const leftFkCol = (linkTable as any)[leftFk]
      // biome-ignore lint/suspicious/noExplicitAny: Drizzle dynamic column access
      const rightFkCol = (linkTable as any)[rightFk]

      const { eq, and } = await import('drizzle-orm')
      await db.delete(linkTable).where(and(eq(leftFkCol, leftId), eq(rightFkCol, rightId)))

      const eventBus = app.infra?.eventBus
      if (eventBus) {
        await eventBus.emit(`${leftLower}.${rightLower}.unlinked`, { [leftFk]: leftId, [rightFk]: rightId })
      }

      return { success: true }
    },
  })

  return commands
}
