// @ts-nocheck — Template file: deps (@manta/cli, jiti) are resolved in the target project
// Auto-generated by @manta/host-nitro — DO NOT EDIT
//
// IMPORTANT: imports use @manta/cli SUBPATHS (not the barrel '@manta/cli') to avoid
// pulling in dev commands → host-nitro → vite → webpack → xml2js into the production
// serverless bundle. The barrel re-exports devCommand/buildCommand which transitively
// import 900kB+ of dev tooling that crashes at runtime on Vercel ("Cannot find xml2js").

import { bootstrapApp } from '@manta/cli/bootstrap'

// biome-ignore lint/suspicious/noExplicitAny: dynamic bootstrap result
let _bootstrapped: any = null

async function bootstrap() {
  if (_bootstrapped) return _bootstrapped

  const cwd = process.cwd()

  // Load .env
  const { loadEnv } = await import('@manta/cli/env')
  loadEnv(cwd)

  // Build jiti importer for .ts files (Nitro runtime has no TS loader)
  const { createJiti } = await import('jiti')
  const jiti = createJiti(cwd)
  // biome-ignore lint/suspicious/noExplicitAny: dynamic module import
  const importFn = (path: string) => jiti.import(path) as Promise<any>

  // Load config via jiti
  const { resolve } = await import('node:path')
  const { loadConfig } = await import('@manta/cli/config')
  const config = await loadConfig(cwd, { importFn })

  _bootstrapped = await bootstrapApp({ config, cwd, mode: 'dev', importFn })
  return _bootstrapped
}

const _promise = bootstrap()

export async function getMantaAdapter() {
  const { adapter } = await _promise
  return adapter
}

export async function getMantaApp() {
  const { app } = await _promise
  return app
}
