// @ts-nocheck — Template file: deps (@manta/cli, jiti) are resolved in the target project
// Auto-generated by @manta/host-nitro — DO NOT EDIT
//
// Uses STATIC imports everywhere (bundled by Nitro at build time):
//  - @manta/cli subpaths (not the barrel) to avoid pulling in dev tooling
//  - manifest.ts (generated by manta build) with pre-imported user modules
//  - No jiti, no readdirSync, no dynamic import of .ts files
//
// This is the serverless-safe bootstrap: all user code is statically traced
// and bundled by Nitro/rolldown. No filesystem access at runtime.

import { bootstrapApp } from '@manta/cli/bootstrap'
import { loadEnv } from '@manta/cli/env'
import mantaConfigModule from './manta.config'

// Build-time manifest: pre-discovered resources + pre-imported modules.
// Generated by `manta build --preset vercel` in packages/cli/src/build/generate-manifest.ts.
// If the manifest doesn't exist (dev mode), fallback to runtime discovery.
let manifest: {
  moduleExports: Record<string, unknown>
  preloadedResources: unknown
  preloadedPluginResources: unknown[]
} | null = null
try {
  manifest = require('./manifest')
} catch {
  // Manifest not available (dev mode or non-serverless build) — runtime discovery will be used
}

// biome-ignore lint/suspicious/noExplicitAny: dynamic bootstrap result
let _bootstrapped: any = null

async function bootstrap() {
  if (_bootstrapped) return _bootstrapped

  const cwd = process.cwd()
  loadEnv(cwd)

  const config = mantaConfigModule.default ?? mantaConfigModule

  if (manifest) {
    // Serverless path: use build-time manifest (no filesystem access, no jiti)
    _bootstrapped = await bootstrapApp({
      config,
      cwd,
      mode: 'dev',
      preloadedResources: manifest.preloadedResources as any,
      preloadedImports: manifest.moduleExports as Record<string, Record<string, unknown>>,
    })
  } else {
    // Dev path: use jiti for runtime .ts loading
    const { createJiti } = await import('jiti')
    const jiti = createJiti(cwd)
    // biome-ignore lint/suspicious/noExplicitAny: dynamic module import
    const importFn = (path: string) => jiti.import(path) as Promise<any>

    _bootstrapped = await bootstrapApp({ config, cwd, mode: 'dev', importFn })
  }

  return _bootstrapped
}

const _promise = bootstrap()

export async function getMantaAdapter() {
  const { adapter } = await _promise
  return adapter
}

export async function getMantaApp() {
  const { app } = await _promise
  return app
}
