// Auto-generates Vite config for the admin dashboard (Tailwind v4 via Vite plugin).
// Written to .manta/admin/ so it never pollutes the user's project root.

import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'

/**
 * Ensure build config exists for a SPA.
 * If spaName is 'admin' or omitted, generates the full Manta dashboard config.
 * For other SPAs, generates a minimal Vite config pointing to src/spa/{name}/.
 * Returns the absolute path to the generated vite.config.ts.
 */
export function ensureAdminConfigs(cwd: string, spaName?: string): string {
  if (spaName && spaName !== 'admin') {
    // V2: custom SPA — generate a minimal Vite config
    const spaConfigDir = resolve(cwd, '.manta', `spa-${spaName}`)
    mkdirSync(spaConfigDir, { recursive: true })

    const viteConfigPath = join(spaConfigDir, 'vite.config.ts')
    const spaRoot = resolve(cwd, 'src', 'spa', spaName)

    writeFileSync(
      viteConfigPath,
      `import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  root: '${spaRoot.replace(/\\/g, '/')}',
  base: '/${spaName}/',
  plugins: [react()],
  server: { hmr: true },
  build: { outDir: '${resolve(cwd, 'public', spaName).replace(/\\/g, '/')}', emptyOutDir: true },
})
`,
    )

    return viteConfigPath
  }

  // Legacy: admin dashboard config
  const adminConfigDir = resolve(cwd, '.manta', 'admin')
  mkdirSync(adminConfigDir, { recursive: true })

  const viteConfigPath = join(adminConfigDir, 'vite.config.ts')

  writeFileSync(viteConfigPath, generateViteConfig(cwd))

  return viteConfigPath
}

function resolveDashboardPaths(cwd: string): {
  dashboard: string
  dashboardCore: string
  uiPkg: string
  isMonorepo: boolean
} {
  // Try to resolve from node_modules first (published packages)
  try {
    const dashboardPkg = dirname(require.resolve('@manta/dashboard/package.json', { paths: [cwd] }))
    const dashboardCorePkg = dirname(require.resolve('@manta/dashboard-core/package.json', { paths: [cwd] }))
    const uiPkg = dirname(require.resolve('@manta/ui/package.json', { paths: [cwd] }))
    return {
      dashboard: join(dashboardPkg, 'src/index.tsx'),
      dashboardCore: join(dashboardCorePkg, 'src'),
      uiPkg: join(uiPkg, 'src'),
      isMonorepo: false,
    }
  } catch {
    // Fallback: monorepo structure (workspace:* dependencies)
    const monoRoot = resolve(cwd, '../..')
    const dashboard = resolve(monoRoot, 'packages/dashboard/src/index.tsx')
    const dashboardCore = resolve(monoRoot, 'packages/dashboard-core/src')
    const uiPkg = resolve(monoRoot, 'packages/ui/src')

    if (existsSync(dashboard)) {
      return { dashboard, dashboardCore, uiPkg, isMonorepo: true }
    }

    // Last resort — relative to cwd
    return {
      dashboard: resolve(cwd, 'node_modules/@manta/dashboard/src/index.tsx'),
      dashboardCore: resolve(cwd, 'node_modules/@manta/dashboard-core/src'),
      uiPkg: resolve(cwd, 'node_modules/@manta/ui/src'),
      isMonorepo: false,
    }
  }
}

function generateViteConfig(cwd: string): string {
  const paths = resolveDashboardPaths(cwd)
  const adminRoot = resolve(cwd, 'src/admin')
  const outDir = resolve(cwd, 'public/admin')

  return `// Auto-generated by Manta CLI — do not edit
import tailwindcss from '@tailwindcss/vite'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  root: ${JSON.stringify(adminRoot)},
  base: '/admin',
  plugins: [react(), tailwindcss()],
  resolve: {
    alias: {
      '@manta/dashboard': ${JSON.stringify(paths.dashboard)},
      '@manta/dashboard-core': ${JSON.stringify(paths.dashboardCore)},
      '@manta/dashboard-core/index.css': ${JSON.stringify(join(paths.dashboardCore, 'index.css'))},
      '@manta/ui': ${JSON.stringify(join(paths.uiPkg, 'index.ts'))},
    },
  },
  server: {
    port: 5199,
    strictPort: true,
    hmr: { port: 5199 },
  },
  build: {
    outDir: ${JSON.stringify(outDir)},
    emptyOutDir: true,
  },
})
`
}
