// Generated by ts-to-zod
import { z } from 'zod'

export const postHogCaptureInputSchema = z.object({
  distinctId: z.string(),
  event: z.string(),
  properties: z.record(z.string(), z.unknown()).optional(),
  timestamp: z.date().optional(),
  uuid: z.string().optional(),
})

export const postHogIdentifyInputSchema = z.object({
  distinctId: z.string(),
  properties: z.record(z.string(), z.unknown()).optional(),
})

const _assertCaptureMatchesSdkSchema = z.any()

const _assertIdentifyMatchesSdkSchema = z.any()

export const postHogEventSchema = z.object({
  uuid: z.string(),
  event: z.string(),
  distinctId: z.string(),
  timestamp: z.string(),
  properties: z.record(z.string(), z.unknown()),
  personId: z.string().nullable(),
  url: z.string().nullable(),
})

export const postHogPersonSchema = z.object({
  id: z.string(),
  distinctId: z.string(),
  email: z.string().nullable(),
  name: z.string().nullable(),
  createdAt: z.string(),
  properties: z.record(z.string(), z.unknown()),
})

export const postHogInsightSchema = z.object({
  id: z.number(),
  shortId: z.string().nullable(),
  name: z.string(),
  description: z.string().nullable(),
  filters: z.record(z.string(), z.unknown()),
  createdAt: z.string(),
  updatedAt: z.string().nullable(),
})
