// @manta/core/adapters — In-memory adapter implementations for dev/test

export { MockAuthGateway, MockAuthModuleService, MockAuthPort, type TestAuthConfig } from './auth-mock'
export { InMemoryCacheAdapter } from './cache-memory'
export { InMemoryDatabaseAdapter, InMemoryTransaction } from './database-memory'
export { InMemoryEventBusAdapter } from './eventbus-memory'
export { InMemoryFileAdapter } from './file-memory'
export { InMemoryHttpAdapter } from './http-memory'
export { InMemoryJobScheduler } from './job-scheduler-memory'
export { InMemoryLockingAdapter } from './locking-memory'
export { type LogEntry, TestLogger } from './logger-test'
export { InMemoryNotificationAdapter } from './notification-memory'
export { InMemoryRelationalQuery } from './relational-query-memory'
export { InMemoryRepositoryFactory } from './repository-factory-memory'
export { InMemoryRepository } from './repository-memory'
